maintainer       "SpeedyMailer"
maintainer_email "david.mazvovsky@gmail.com"
license          "All rights reserved"
description      "Installs/Configures speedymailer-drone"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends          "apt"
depends          "git"
depends          "ruby"
depends          "rubygems"
